name: test Workerman

on: [ push, pull_request ]

jobs:
  linux_tests:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        php: ["8.1", "8.2", "8.3"]
        #workerman: ["4.1", "5.0"]
      
      fail-fast: false

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, posix, pcntl
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          #coverage: xdebug

      - name: Install dependencies
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --prefer-dist --no-interaction --no-progress --ansi

      - name: Start Workerman 4
        run: |
            sed -i "s|uses(ServerTestCase::class)|//uses(ServerTestCase::class)|g" tests/Pest.php
            php tests/Servers/Workerman4.php start -d

      - name: Execute tests
        run: vendor/bin/pest --colors=always

      - name: Stop Workerman
        run: php tests/Servers/Workerman.php stop
