name: Tests PHP CLI server

on: [ push, pull_request ]

jobs:
  linux_tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        php: ["8.1", "8.2", "8.3"]
      
      fail-fast: false

    name: PHP ${{ matrix.php }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: ${{ matrix.php }}
            extensions: json, posix, pcntl
            ini-values: error_reporting=E_ALL
            tools: composer:v2
            coverage: none

      - name: Install dependencies
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --prefer-dist --no-interaction --no-progress --ansi
    
      - name: Start PHP CLI Server
        run: |
          if [ ${{ matrix.os }} == 'windows-latest' ]; then
            start /b php -S 127.0.0.1:8080 tests/Servers/Php.php
          else
            php -S 127.0.0.1:8080 tests/Servers/Php.php &

      - name: Execute tests
        run: vendor/bin/pest --colors=always
